### ISSUE TITLE
Support apigen config file

### ISSUE THREAD

**Issue by shivapoudel** [cibulka/grunt-apigen#1]
I think it will be great idea to add support for `apigen.neon` file in our project root.
Additionally if the command `apigen` is not available then output the `grunt.fail.message` xD

**Comment by cibulka** [comment]
Sorry for the late reply! It does sound great, but unfortunately I am abandonning this repo in favour of Gulp based solutions. :( I am open to transfering the repo though, see Readme.

**Comment by jjeaton** [comment]
This is definitely something we should support, reopening.

**Comment by shivapoudel** [comment]
Matters time IMO :D
